services:
  timescaledb:
    # define image
    image: timescale/timescaledb-ha:pg16
    container_name: vectorscaledb1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5556:5432"
    volumes:
      # Map your SQL initialization script so it runs on first container startup
    - ./initdb/prepare_similarity_search_service_db.sql:/docker-entrypoint-initdb.d/prepare_similarity_search_service_db.sql

